server:
  port: 8770
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zzfn/cloud-config.git
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true