server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 113.31.126.209
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://47.100.47.169:8761/eureka/