server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://eurekaA:8766/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
spring:
  profiles:
    active: c
  application:
    name: server