server:
  port: 8762
spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
#      routes:
#        - id: article
#          uri: lb://article
#          predicates:
#            - Path=/article/**
#      default-filters:
#        - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: debug