server:
  port: 8762
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
        - id: article
          uri: lb://article
          predicates:
            - Path=/article/**
      default-filters:
        - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://47.100.47.169:8761/eureka,http://113.31.126.209:8761/eureka,
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
logging:
  level:
    org.springframework.cloud.gateway: debug