server:
  port: 8763

spring:
  application:
    name: auth
eureka:
  client:
    service-url:
      defaultZone: http://47.100.47.169:8761/eureka,http://113.31.126.209:8761/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
logging:
  level:
    org.springframework.cloud.gateway: debug