server:
  port: 8762

spring:
  application:
    name: auth
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
logging:
  level:
    org.springframework.cloud.gateway: debug